[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/ar/"
status = 302
force = true
conditions = {Language = ["ar"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/bn/"
status = 302
force = true
conditions = {Language = ["bn"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/id/"
status = 302
force = true
conditions = {Language = ["id"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/de/"
status = 302
force = true
conditions = {Language = ["de"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/en/"
status = 302
force = true
conditions = {Language = ["en"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/es/"
status = 302
force = true
conditions = {Language = ["es"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/fr/"
status = 302
force = true
conditions = {Language = ["fr"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/hi/"
status = 302
force = true
conditions = {Language = ["hi"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/ja/"
status = 302
force = true
conditions = {Language = ["ja"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/kn/"
status = 302
force = true
conditions = {Language = ["kn"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/ko/"
status = 302
force = true
conditions = {Language = ["ko"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/pl/"
status = 302
force = true
conditions = {Language = ["pl"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/pt/"
status = 302
force = true
conditions = {Language = ["pt"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/pt-br/"
status = 302
force = true
conditions = {Language = ["pt-br"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/mi/"
status = 302
force = true
conditions = {Language = ["mi"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/nl/"
status = 302
force = true
conditions = {Language = ["nl"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/no/"
status = 302
force = true
conditions = {Language = ["no"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/fi/"
status = 302
force = true
conditions = {Language = ["fi"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/tr/"
status = 302
force = true
conditions = {Language = ["tr"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/ro/"
status = 302
force = true
conditions = {Language = ["ro"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/ru/"
status = 302
force = true
conditions = {Language = ["ru"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/vi/"
status = 302
force = true
conditions = {Language = ["vi"]}

[[redirects]]
from = "https://asshole.fyi"
to = "https://asshole.fyi/zh/"
status = 302
force = true
conditions = {Language = ["zh"]}

